services:
  wersu-grpc:
    image: kuramasyu/wersu-grpc:dev
    ports:
      - "50052:50052"
    environment:
      GRPC_HOST: 0.0.0.0
      GRPC_PORT: 50052
      GRPC_SPICEDB_CREDENTIALS: "558568b6e7603e3033a0737e2ba3a00b9371b0e962ef13df8f731366b94ae778"
      GRPC_SPICEDB_ADDRESS: "spicedb:50051"
      DATABASE_DSN: "postgres://postgres:postgres@postgres:5432/db?sslmode=disable"
    depends_on:
      - postgres
      - pgweb

  wersu-rest:
    image: ghcr.io/kuramasyu/wersu-rest:dev
    ports:
      - "8080:8080"
    environment:
      REST_HOST: localhost
      REST_PORT: 8080
      DISCORD_CLIENT_ID: ${DISCORD_CLIENT_ID}
      DISCORD_CLIENT_SECRET: ${DISCORD_CLIENT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      DISCORD_REDIRECT_URI: ${DISCORD_REDIRECT_URI}
      FRONTEND_URL: ${FRONTEND_URL}
      GRPC_SERVER_ADDRESS: "wersu-grpc:50052"  # how the GRPC server is internal reachable
      BACKEND_URL: http://localhost:8080  # how the backend is reachable from view of user
    depends_on:
      - wersu-grpc

  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: db
    # ports:
    #   - "5432:5432"
    volumes:
      - ./data/pgvector:/var/lib/postgresql

  pgweb:
    container_name: pgweb_helper
    restart: always
    image: sosedoff/pgweb
    ports: 
      - "8081:8081" 
    links: 
      - postgres:postgres  # my database container is called postgres, not db
    environment:
      - PGWEB_DATABASE_URL=postgres://postgres:postgres@postgres:5432/db?sslmode=disable
    depends_on:
      - postgres
      
  spicedb:
    image: authzed/spicedb:latest
    container_name: spicedb
    command:
      - serve
      - --http-enabled=true
      - --grpc-preshared-key=somerandomkeyhere
    ports:
      - "50051:50051" # gRPC
      - "8443:8443"   # HTTP
    restart: unless-stopped