/**
 * Magic title used for the per-directory README note. WerSu keeps this note
 * invisible to the directory listing and uses its body to drive the
 * directory's display name, description, and image. See `DirectoryEdit`.
 */
export const README_NOTE_TITLE = "README.md";

/**
 * Header regenerated on every directory save. Manual edits to the README
 * inside the editor (e.g. opening `/n/<readmeId>` and writing prose) are
 * preserved in the body below the sentinel.
 */
export const README_SENTINEL =
  "# do not change, this is autogenerated and used by WerSu";

export interface ReadmeHeader {
  name: string;
  description?: string;
  imageUrl?: string;
}

/**
 * Builds the README note body for a directory. Returns a single string the
 * backend accepts (never empty when the header carries any field). The
 * shape is:
 *
 *     # <name>
 *     ![directoryImage](<imageUrl>)
 *
 *     <description>
 *
 *     # do not change, this is autogenerated and used by WerSu
 *
 *     <body>
 *
 * Optional lines (image, description) are omitted when absent. The sentinel
 * is always present so the parser can locate the auto-generated block.
 */
export function serializeReadme(
  header: ReadmeHeader,
  body: string = "",
): string {
  const sections: string[] = [];

  sections.push(`# ${header.name}`);

  if (header.imageUrl && header.imageUrl.trim().length > 0) {
    sections.push(`![directoryImage](${header.imageUrl.trim()})`);
  }

  if (header.description && header.description.trim().length > 0) {
    sections.push("");
    sections.push(header.description.trim());
  }

  sections.push("");
  sections.push(README_SENTINEL);

  if (body.trim().length > 0) {
    sections.push("");
    sections.push(body.trim());
  }

  return sections.join("\n");
}

/**
 * Returns a short, single-line preview of the auto-generated header of a
 * README body. Drops everything below `README_SENTINEL` (the user-authored
 * section) and clips to `maxLength` characters. Used by the image upload
 * modal to give the user a hint of what they're attaching to.
 */
export function getReadmePreview(
  content: string | undefined,
  maxLength = 300,
): string {
  if (!content) {
    return "";
  }
  const sentinelIndex = content.indexOf(README_SENTINEL);
  const header =
    sentinelIndex === -1 ? content : content.slice(0, sentinelIndex);
  const collapsed = header.replace(/\s+/g, " ").trim();
  if (collapsed.length <= maxLength) {
    return collapsed;
  }
  return `${collapsed.slice(0, maxLength).trimEnd()}…`;
}
