import { useCallback, useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useQueryClient } from "@tanstack/react-query";
import { DirectoryApi } from "../../api/DirectoryApi";
import type { DirectoryReply } from "../../api/models/directory";
import type { MinimalNote } from "../../api/models/search";
import { getNoteApi, type INoteApi } from "../../api/NoteApi";
import { useDirectory } from "../../api/queries/useDirectoryQuery";
import { useDirectoryNotesQuery } from "../../api/queries/useDirectoryNotesQuery";
import { useDirectoryStore } from "../../zustand/useDirectoryStore";
import useInfoStore, { SnackbarUpdateImpl } from "../../zustand/InfoStore";
import { README_NOTE_TITLE, serializeReadme } from "../../utils/readme";
import { useDirectoryFormShell } from "./directoryFormShell";
import {
  ROOT_PARENT_ID,
  createDirectoryApi,
  invalidateDirectoryQueries,
  labelOf,
  resolveParentIds,
} from "./directoryFormShared";

const extractReadmeBody = (content: string | undefined): string => {
  if (!content) {
    return "";
  }
  // `serializeReadme` always emits the sentinel. Anything after it is
  // user-authored body; anything before it is the auto-generated
  // header. We keep the body so a round-trip through the editor
  // doesn't lose manual prose.
  const sentinel = "# do not change, this is autogenerated and used by WerSu";
  const parts = content.split(sentinel);
  return parts.length > 1 ? parts.slice(1).join(sentinel).trim() : "";
};

const findReadme = (notes: MinimalNote[] | undefined): MinimalNote | null => {
  if (!notes) {
    return null;
  }
  return notes.find((note) => note.title === README_NOTE_TITLE) ?? null;
};

export interface UseDirectoryEditFormOptions {
  /**
   * Optional override for the directory id being edited. When omitted,
   * the hook falls back to the route `:id` param (the existing
   * route-driven behaviour). The `CreateDirectoryModal` passes this in
   * directly so it can mount the edit flow from the directory view
   * without a dedicated `/d/:id/edit` route hop.
   */
  directoryId?: string;
  /**
   * Optional cancel handler. When provided, it runs instead of the
   * default `navigate(-1)`. The modal uses this to close the dialog
   * without leaving the host page.
   */
  onCancel?: () => void;
}

export interface UseDirectoryEditFormResult {
  // Hydration
  directory: DirectoryReply | null;
  isLoadingDirectory: boolean;

  // Form fields (from the shared shell)
  name: string;
  description: string;
  imageUrl: string;
  setName: (value: string) => void;
  setDescription: (value: string) => void;
  setImageUrl: (value: string) => void;
  sortedDirectories: DirectoryReply[];

  // Parent selector
  parentLabel: string;
  setParent: (value: string) => void;
  parentIsValid: boolean;
  resolveParentForPayload: () => string;

  // README state (Edit-only)
  readmeNoteId: string | null;
  readmeBody: string;
  setReadmeBody: (value: string) => void;
  /**
   * Resolves the current README note id, creating the note (and
   * assigning it to this directory) on the server if one doesn't
   * exist. The image upload modal calls this on every upload to
   * guarantee a stable id for the `linkAttachment` step.
   */
  getReadmeNoteId: () => Promise<string | null>;

  // Save / delete
  isSaving: boolean;
  isDeleting: boolean;
  handleSave: () => Promise<void>;
  handleDelete: () => Promise<void>;
  handleCancel: () => void;
  /** True when the form is pristine vs. the underlying record. */
  hasDirectoryId: boolean;
}

/**
 * Owns the `DirectoryEdit` form's data flow:
 *
 * - hydrates the directory list (shared with `DirectoryCreate` via
 *   `useDirectoryFormShell`)
 * - fetches the single directory record and seeds the form from it
 * - discovers the directory's README note and exposes its body for
 *   the editor
 * - implements `handleSave` (PATCH directory + persist README + move
 *   parent) and `handleDelete` (DELETE directory)
 *
 * The view is presentational; all state and side effects live here.
 */
export function useDirectoryEditForm(
  options: UseDirectoryEditFormOptions = {},
): UseDirectoryEditFormResult {
  const { id: routeId } = useParams();
  const navigate = useNavigate();
  const { directoriesById, upsertDirectory, removeDirectory } =
    useDirectoryStore();
  const { setMessage } = useInfoStore();
  const queryClient = useQueryClient();
  const noteApi: INoteApi = getNoteApi();

  // Prefer the explicit `directoryId` option; fall back to the route
  // `:id` so the existing `/d/:id/edit` page keeps working. The modal
  // passes the option directly when mounted outside the edit route.
  const id = options.directoryId ?? routeId;

  const [readmeNoteId, setReadmeNoteId] = useState<string | null>(null);
  const [readmeBody, setReadmeBody] = useState<string>("");
  const [readmeHydratedFor, setReadmeHydratedFor] = useState<string | null>(
    null,
  );
  const [isSaving, setIsSaving] = useState(false);
  const [isDeleting, setIsDeleting] = useState(false);

  // 1. Directory metadata: prefer the cached store record (kept fresh
  //    by the parent list query), fall back to a single-record fetch
  //    via the TanStack query hook.
  const cachedDirectory = id ? directoriesById[id] : undefined;
  const { data: fetchedDirectory, isPending: isDirectoryPending } =
    useDirectory(cachedDirectory ? undefined : id);

  useEffect(() => {
    if (fetchedDirectory) {
      upsertDirectory(fetchedDirectory);
    }
  }, [fetchedDirectory, upsertDirectory]);

  const directory: DirectoryReply | null =
    cachedDirectory ?? fetchedDirectory ?? null;
  const isLoadingDirectory = !!id && isDirectoryPending && !cachedDirectory;

  // 2. README discovery. The hook fetches the directory's notes; the
  //    README (if any) is the entry with `title === "README.md"`. We
  //    hydrate form state once per directory id.
  const { data: directoryNotesReply } = useDirectoryNotesQuery(id, {
    limit: 100,
  });

  useEffect(() => {
    if (!id || !directoryNotesReply) {
      return;
    }
    if (readmeHydratedFor === id) {
      return;
    }
    const readme = findReadme(directoryNotesReply.notes);
    setReadmeNoteId(readme?.id ?? null);
    setReadmeBody(extractReadmeBody(readme?.stripped_content));
    setReadmeHydratedFor(id);
  }, [id, directoryNotesReply, readmeHydratedFor]);

  // Reset the hydration marker when the user navigates to a different
  // directory so the next mount re-reads the README.
  useEffect(() => {
    setReadmeHydratedFor(null);
  }, [id]);

  // 3. Form state. The shared shell seeds the form from the
  //    `DirectoryReply` once it first arrives; subsequent edits are
  //    owned by the user. The form's `Main.tsx` keys the form body
  //    on the route `:id`, so navigating from `/d/A/edit` to
  //    `/d/B/edit` unmounts and remounts the whole tree — this hook
  //    re-initialises with B's data, no manual reset needed here.
  const shell = useDirectoryFormShell({
    initial: directory ?? undefined,
    initialParentId: directory?.parent_dir_ids?.[0],
  });

  const getReadmeNoteId = useCallback(async (): Promise<string | null> => {
    if (!id) {
      return null;
    }
    if (readmeNoteId) {
      return readmeNoteId;
    }
    const trimmedName = shell.name.trim() || "Untitled";
    const serializedReadme = serializeReadme(
      {
        name: trimmedName,
        description: shell.description,
        imageUrl: shell.imageUrl,
      },
      shell.pendingImagePreviewUrl ? "" : readmeBody,
    );
    try {
      const created = await noteApi.post(README_NOTE_TITLE, serializedReadme);
      const moved = await noteApi.patchDirectory(created.id, id);
      if (!moved) {
        setMessage(
          new SnackbarUpdateImpl(
            "README created, but failed to assign to this directory",
            "warning",
          ),
        );
        return null;
      }
      setReadmeNoteId(created.id);
      queryClient.invalidateQueries({
        queryKey: ["directory", "notes", id],
      });
      setMessage(
        new SnackbarUpdateImpl(
          "Created README.md to link the uploaded image",
          "info",
        ),
      );
      return created.id;
    } catch (error) {
      console.error("Failed to create README note", error);
      return null;
    }
  }, [
    id,
    readmeNoteId,
    shell.name,
    shell.description,
    shell.imageUrl,
    shell.pendingImagePreviewUrl,
    readmeBody,
    noteApi,
    queryClient,
    setMessage,
  ]);

  const handleSave = async () => {
    if (!id) {
      return;
    }
    if (id === ROOT_PARENT_ID) {
      setMessage(
        new SnackbarUpdateImpl("Root directory cannot be edited", "info"),
      );
      return;
    }

    const trimmedName = shell.name.trim();
    if (!trimmedName) {
      setMessage(new SnackbarUpdateImpl("Name is required", "warning"));
      return;
    }

    // The parent field is a free-text input: the user can type
    // any value, even one that doesn't match a known directory.
    // We refuse to save when the value is unresolved so we don't
    // silently move the directory to a non-existent parent.
    if (!shell.parent.parentIsValid) {
      setMessage(
        new SnackbarUpdateImpl(
          `Parent directory "${shell.parent.parentLabel}" does not exist. Pick a directory from the list, or clear the field for top level.`,
          "error",
        ),
      );
      return;
    }

    const current = directoriesById[id];
    const nextParentIds = resolveParentIds(shell.parent.resolveForPayload());

    const serializedReadme = serializeReadme(
      {
        name: trimmedName,
        description: shell.description,
        imageUrl: shell.imageUrl,
      },
      readmeBody,
    );

    setIsSaving(true);
    try {
      // 1. Persist the README note. Regenerate the header on every
      //    save; preserve the user-authored body below the sentinel.
      let nextReadmeId = readmeNoteId;
      if (nextReadmeId) {
        const patched = await noteApi.patch(
          nextReadmeId,
          README_NOTE_TITLE,
          serializedReadme,
        );
        if (!patched) {
          setMessage(
            new SnackbarUpdateImpl(
              "Directory updated, but failed to save README",
              "warning",
            ),
          );
        }
      } else {
        const created = await noteApi.post(README_NOTE_TITLE, serializedReadme);
        const moved = await noteApi.patchDirectory(created.id, id);
        if (!moved) {
          setMessage(
            new SnackbarUpdateImpl(
              "README created, but failed to assign to this directory",
              "warning",
            ),
          );
        }
        nextReadmeId = created.id;
      }

      // 2. Sync directory metadata (name / description / image_url).
      const shouldPatchDetails =
        !current ||
        trimmedName !== labelOf(current) ||
        shell.description !== (current.description ?? "") ||
        shell.imageUrl !== (current.image_url ?? "");

      if (shouldPatchDetails) {
        const updated = await createDirectoryApi().patch({
          id,
          display_name: trimmedName,
          description: shell.description || undefined,
          image_url: shell.imageUrl || undefined,
        });
        if (!updated) {
          setMessage(
            new SnackbarUpdateImpl("Failed to update directory", "error"),
          );
          return;
        }
        upsertDirectory(updated);
      }

      // 3. Move the directory if the parent changed.
      const currentParentId = current?.parent_dir_ids?.[0] ?? ROOT_PARENT_ID;
      const nextParentId =
        nextParentIds === null ? ROOT_PARENT_ID : nextParentIds[0];
      const parentChanged = currentParentId !== nextParentId;

      if (parentChanged) {
        const updatedParent = await createDirectoryApi().setParent(
          id,
          nextParentIds,
        );
        if (!updatedParent) {
          setMessage(
            new SnackbarUpdateImpl(
              "Directory updated, but failed to move directory",
              "warning",
            ),
          );
          return;
        }
        upsertDirectory(updatedParent);
      }

      setReadmeNoteId(nextReadmeId);

      invalidateDirectoryQueries(queryClient, id, nextParentId);
      if (nextReadmeId) {
        queryClient.invalidateQueries({ queryKey: ["notes", nextReadmeId] });
      }

      setMessage(new SnackbarUpdateImpl("Directory saved", "success"));
      navigate(`/d/${id}`);
    } finally {
      setIsSaving(false);
    }
  };

  const handleDelete = async () => {
    if (!id || id === ROOT_PARENT_ID) {
      return;
    }
    const confirmed = window.confirm(
      "Delete this directory? Notes inside may become unassigned.",
    );
    if (!confirmed) {
      return;
    }
    setIsDeleting(true);
    try {
      const deleted = await createDirectoryApi().delete(id);
      if (!deleted) {
        setMessage(
          new SnackbarUpdateImpl("Failed to delete directory", "error"),
        );
        return;
      }
      removeDirectory(id);
      setMessage(new SnackbarUpdateImpl("Directory deleted", "success"));
      navigate("/");
    } finally {
      setIsDeleting(false);
    }
  };

  const handleCancel = () => {
    if (options.onCancel) {
      options.onCancel();
      return;
    }
    navigate(-1);
  };

  return {
    directory,
    isLoadingDirectory,
    name: shell.name,
    description: shell.description,
    imageUrl: shell.imageUrl,
    setName: shell.setName,
    setDescription: shell.setDescription,
    setImageUrl: shell.setImageUrl,
    sortedDirectories: shell.sortedDirectories,
    parentLabel: shell.parent.parentLabel,
    setParent: shell.parent.setParent,
    parentIsValid: shell.parent.parentIsValid,
    resolveParentForPayload: shell.parent.resolveForPayload,
    readmeNoteId,
    readmeBody,
    setReadmeBody,
    getReadmeNoteId,
    isSaving,
    isDeleting,
    handleSave,
    handleDelete,
    handleCancel,
    hasDirectoryId: !!id,
  };
}
